Repository undistro/zora, pull requests merged in 2022-10, with the labels that each got.

#146 Ignoring OK level issues (POP-406)
  worker/report/popeye/parse.go
  worker/report/popeye/testdata/test_report_2.json
Labels: bug

#147 bump chart version to v0.3.8
  charts/zora/Chart.yaml
  charts/zora/README.md
  main.go
Labels: documentation, enhancement

#148 Get only issues from last scans
  charts/zora/Chart.yaml
  charts/zora/README.md
  handlers/issues.go
  main.go
Labels: bug

#150 Adapt <manifests> target to license headers
  Makefile
  hack/patches/rbac/service_account.patch
Labels: enhancement

#151 Add suspend field in plugin status
  apis/zora/v1alpha1/clusterscan_types.go
  apis/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  controllers/zora/clusterscan_controller.go
  openapi.yaml
  payloads/clusters.go
  payloads/clusters_test.go
  payloads/testdata/clusterscan/suspend.yml
  payloads/testdata/payload/10.json
  pkg/apis/zz_generated.deepcopy.go
  pkg/discovery/zz_generated.deepcopy.go
Labels: enhancement

#152 Cronjob Job Limit
  apis/zora/v1alpha1/clusterscan_types.go
  apis/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  pkg/plugins/cronjobs/cronjob.go
Labels: enhancement

#155 Update docs about prepare the target cluster
  docs/target-cluster.md
Labels: documentation

#157 Update target cluster docs
  docs/target-cluster.md
Labels: documentation

#158 Fix target cluster doc
  docs/target-cluster.md
Labels: documentation

#159 Kind load over local reg
  .github/workflows/docker-push.yaml
  Makefile
  hack/make/config.mk
  hack/scripts/setup_kind.sh
  hack/scripts/setup_local_registry.sh
Labels: enhancement

#161 Notify SaaS when the helm release is installed
  charts/zora/templates/saas/install.yaml
  charts/zora/values.yaml
Labels: enhancement

#162 Cluster saas send
  controllers/zora/cluster_controller.go
  controllers/zora/saas_controller.go
  main.go
  pkg/payloads/v1alpha1/clusters.go
  pkg/payloads/v1alpha1/issues.go
Labels: enhancement

#164 Saas url validation
  controllers/zora/saas_controller.go
  main.go
Labels: enhancement

#166 SaaS client and hooks
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/operator/rbac.yaml
  charts/zora/values.yaml
  config/rbac/role.yaml
  controllers/zora/cluster_controller.go
  controllers/zora/clusterscan_controller.go
  controllers/zora/saas_controller.go
  handlers/clusters.go
  main.go
  pkg/payloads/v1alpha1/clusters.go
  pkg/payloads/v1alpha1/clusters_test.go
  pkg/payloads/v1alpha1/issues.go
  pkg/saas/client.go
  pkg/saas/hooks.go
Labels: enhancement

#165 Delete dangling <Cronjobs>
  controllers/zora/clusterscan_controller.go
Labels: enhancement
