Repository undistro/zora, pull requests merged in 2022-11, with the labels that each got.

#168 Fix <targetcluster.sh> whitespace
  docs/targetcluster.sh
Labels: bug, enhancement

#169 add rancher admonition in docs
  docs/target-cluster.md
Labels: documentation

#171 Document Zora setup requirements
  docs/install.md
Labels: documentation, enhancement

#172 Cluster sample unique name
  docs/target-cluster.md
  docs/targetcluster.sh
Labels: documentation, enhancement

#173 Update workflows and replacing registry.undistro.io
  .github/workflows/docker-push.yaml
  .github/workflows/docker.yaml
  .github/workflows/docs.yaml
  .github/workflows/helm-push.yaml
  .github/workflows/hml.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.server
  Dockerfile.worker
  Makefile
  charts/zora/Chart.yaml
  charts/zora/README.md
  charts/zora/README.md.gotmpl
  charts/zora/templates/tests/test-connection.yaml
  charts/zora/values-hml.yaml
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_kubescape.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  docs/install.md
  hack/patches/kubescape_plugin.patch
  hack/patches/popeye_plugin.patch
  main.go
Labels: enhancement

#174 Add info in docs about chart repository URL
  charts/zora/README.md
  charts/zora/README.md.gotmpl
  docs/install.md
Labels: documentation

#175 Mike docs
  .github/workflows/release.yaml
  Makefile
  hack/make/config.mk
  mkdocs.yml
Labels: documentation, enhancement

#176 Saas update
  .github/workflows/docker-push.yaml
  .github/workflows/docker.yaml
  .github/workflows/docs.yaml
  .github/workflows/helm-push.yaml
  .github/workflows/hml.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.server
  Dockerfile.worker
  Makefile
  charts/zora/Chart.yaml
  charts/zora/README.md
  charts/zora/README.md.gotmpl
  charts/zora/values-hml.yaml
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_kubescape.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  controllers/zora/clusterscan_controller.go
  docs/install.md
  docs/target-cluster.md
  docs/targetcluster.sh
  hack/make/config.mk
  hack/patches/kubescape_plugin.patch
  hack/patches/popeye_plugin.patch
  main.go
  mkdocs.yml
Labels: documentation, enhancement

#177 Set prefix on Saas hook
  pkg/saas/client.go
Labels: enhancement

#179 fix Dockerfile.server
  Dockerfile.server
Labels: bug
