Repository undistro/zora, pull requests merged in 2022-09, with the labels that each got.

#136 Add FOSSA status badge in README.md
  README.md
Labels: documentation

#137 update README.md logo
  docs/assets/logo-github.png
Labels: documentation

#138 add href and alt in logo image at README.md
  README.md
Labels: documentation

#139 New scan schedule format
  apis/zora/v1alpha1/clusterscan_types.go
  apis/zora/v1alpha1/clusterscan_types_test.go
  apis/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  config/samples/zora_v1alpha1_clusterscan.yaml
  controllers/zora/clusterscan_controller.go
  hack/scripts/setup_zora_view.sh
  payloads/testdata/clusterscan/all_plugins_active.yml
  payloads/testdata/clusterscan/all_plugins_active_1st.yml
  payloads/testdata/clusterscan/all_plugins_failed.yml
  payloads/testdata/clusterscan/next.yml
  payloads/testdata/clusterscan/ok.yml
  payloads/testdata/clusterscan/plugins_active_and_complete.yml
  payloads/testdata/clusterscan/plugins_active_and_failed.yml
  payloads/testdata/clusterscan/plugins_complete_and_failed.yml
  pkg/plugins/cronjobs/cronjob.go
Labels: enhancement

#120 Saas operator
  charts/zora/templates/operator/rbac.yaml
  config/rbac/role.yaml
  controllers/zora/saas_controller.go
  handlers/cluster.go
  handlers/clusters.go
  handlers/issues.go
  main.go
  pkg/payloads/v1alpha1/clusters.go
  pkg/payloads/v1alpha1/clusters_test.go
  pkg/payloads/v1alpha1/issues.go
  pkg/payloads/v1alpha1/issues_test.go
  pkg/payloads/v1alpha1/testdata/cluster/always_disconnected.yml
  pkg/payloads/v1alpha1/testdata/cluster/always_without_metrics.yml
  pkg/payloads/v1alpha1/testdata/cluster/disconnected.yml
  pkg/payloads/v1alpha1/testdata/cluster/ok.yml
  pkg/payloads/v1alpha1/testdata/cluster/without_metrics.yml
  pkg/payloads/v1alpha1/testdata/cluster/without_provider.yml
  pkg/payloads/v1alpha1/testdata/cluster/without_provider_and_metrics.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/all_plugins_active.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/all_plugins_active_1st.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/all_plugins_failed.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/next.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/ok.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/plugins_active_and_complete.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/plugins_active_and_failed.yml
  pkg/payloads/v1alpha1/testdata/clusterscan/plugins_complete_and_failed.yml
  pkg/payloads/v1alpha1/testdata/payload/1.json
  pkg/payloads/v1alpha1/testdata/payload/2.json
  pkg/payloads/v1alpha1/testdata/payload/3.json
  pkg/payloads/v1alpha1/testdata/payload/4.json
  pkg/payloads/v1alpha1/testdata/payload/5.json
  pkg/payloads/v1alpha1/testdata/payload/6.json
  pkg/payloads/v1alpha1/testdata/payload/7.json
  pkg/payloads/v1alpha1/testdata/payload/8.json
  pkg/payloads/v1alpha1/testdata/payload/9.json
Labels: enhancement

#140 add architecture image into docs
  docs/assets/arch.png
  docs/index.md
Labels: documentation

#142 Update issues URL
  worker/report/parse_test.go
  worker/report/popeye/parse_test.go
  worker/report/popeye/parse_types.go
Labels: documentation, enhancement

#144 Rename github org to undistro
  CONTRIBUTING.md
  PROJECT
  README.md
  apis/zora/v1alpha1/cluster_types.go
  apis/zora/v1alpha1/clusterscan_types.go
  apis/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/Chart.yaml
  cmd/server/main.go
  controllers/zora/cluster_controller.go
  controllers/zora/clusterscan_controller.go
  controllers/zora/suite_test.go
  go.mod
  handlers/cluster.go
  handlers/clusters.go
  handlers/issues.go
  main.go
  mkdocs.yml
  payloads/clusters.go
  payloads/clusters_test.go
  payloads/issues.go
  payloads/issues_test.go
  pkg/clientset/versioned/clientset.go
  pkg/clientset/versioned/fake/clientset_generated.go
  pkg/clientset/versioned/fake/register.go
  pkg/clientset/versioned/scheme/register.go
  pkg/clientset/versioned/typed/zora/v1alpha1/cluster.go
  pkg/clientset/versioned/typed/zora/v1alpha1/clusterissue.go
  pkg/clientset/versioned/typed/zora/v1alpha1/clusterscan.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_cluster.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_clusterissue.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_clusterscan.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_zora_client.go
  pkg/clientset/versioned/typed/zora/v1alpha1/zora_client.go
  pkg/plugins/cronjobs/cronjob.go
  worker/config/config.go
  worker/main.go
  worker/report/kubescape/parse.go
  worker/report/kubescape/parse_test.go
  worker/report/parse.go
  worker/report/parse_test.go
  worker/report/popeye/parse.go
  worker/report/popeye/parse_test.go
  worker/report/popeye/parse_types.go
  worker/run/run.go
  worker/run/run_test.go
Labels: enhancement
