Repository undistro/zora, pull requests merged in 2023-03, with the labels that each got.

#204 Feat/multi platform support
  .github/workflows/docker.yaml
  Dockerfile
  Dockerfile.worker
  charts/zora/README.md
  charts/zora/values.yaml
Labels: enhancement

#206 Popeye multi-platform image
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  hack/patches/popeye_plugin.patch
Labels: enhancement

#205 fail popeye scan for forbidden errors
  worker/report/popeye/parse.go
  worker/report/popeye/parse_test.go
  worker/report/popeye/testdata/test_report_6.json
Labels: bug :bug:

#207 docs: split commands and outputs
  docs/cluster-scan.md
  docs/connect-cluster.md
  docs/target-cluster.md
Labels: documentation :page_facing_up:

#208 remove server component
  .github/workflows/docker.yaml
  Dockerfile.server
  Makefile
  cmd/server/main.go
  go.mod
  go.sum
  hack/make/misc.mk
  handlers/base.go
  handlers/cluster.go
  handlers/clusters.go
  handlers/health.go
  handlers/issues.go
  openapi.yaml
Labels: enhancement

#210 zora version to saas as header
  charts/zora/templates/operator/deployment.yaml
  main.go
  pkg/saas/client.go
Labels: enhancement
