Repository undistro/zora, pull requests merged in 2024-02, with the labels that each got.

#239 create MAINTAINERS.md
  MAINTAINERS.md
Labels: documentation :page_facing_up:

#241 UD-1190: Add support for plugin pod annotations and plugin service ac…
  api/zora/v1alpha1/plugin_types.go
  api/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/README.md
  charts/zora/crds/zora.undistro.io_plugins.yaml
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/plugins/marvin.yaml
  charts/zora/templates/plugins/popeye.yaml
  charts/zora/templates/plugins/trivy.yaml
  charts/zora/values.yaml
  cmd/main.go
  config/crd/bases/zora.undistro.io_plugins.yaml
  docs/configuration/aws-elastic-container-registry.md
  internal/controller/zora/clusterscan_controller.go
  mkdocs.yml
  pkg/plugins/cronjob.go
Labels: enhancement

#242 bump popeye version to 0.11.3
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  config/samples/zora_v1alpha1_plugin_popeye_all.yaml
  docs/plugins/index.md
  docs/plugins/popeye.md
Labels: dependencies

#240 Add HTTPS Proxy Support
  charts/zora/README.md
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/plugins/trivy.yaml
  charts/zora/values.yaml
  cmd/main.go
  docs/configuration/https-proxy.md
  mkdocs.yml
Labels: documentation :page_facing_up:, enhancement

#243 UD-1202: Update the install hook to use the proxy configuration
  charts/zora/templates/hooks/install.yaml
Labels: enhancement

#244 UD-1199: Update helm templates and cronjob creation to enforce correc…
  charts/zora/templates/_helpers.tpl
  charts/zora/templates/clusterscan/clusterscan.yaml
  internal/controller/zora/clusterscan_controller.go
  internal/controller/zora/utils.go
Labels: bug :bug:

#245 Expose plugins `env` and `envFrom` as helm chart parameters
  charts/zora/README.md
  charts/zora/templates/plugins/marvin.yaml
  charts/zora/templates/plugins/popeye.yaml
  charts/zora/templates/plugins/trivy.yaml
  charts/zora/values.yaml
Labels: enhancement

#247 Add documentation page for scanning ACR images
  docs/configuration/acr.md
  docs/configuration/aws-elastic-container-registry.md
  mkdocs.yml
Labels: documentation :page_facing_up:

#249 Add permission to Zora Operator delete service accounts
  charts/zora/templates/operator/rbac.yaml
  config/rbac/role.yaml
  internal/controller/zora/clusterscan_controller.go
Labels: bug :bug:
