Repository undistro/zora, pull requests merged in 2024-04, with the labels that each got.

#264 UD-1350: Update popeye to v0.21.3
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  config/samples/zora_v1alpha1_plugin_popeye_all.yaml
  docs/plugins/index.md
  docs/plugins/popeye.md
Labels: enhancement

#263 Fix sum of issues
  Makefile
  api/zora/v1alpha1/clusterscan_types.go
  charts/zora/Chart.yaml
  charts/zora/README.md
  config/samples/zora_v1alpha1_clusterscan_misconfig.yaml
  config/samples/zora_v1alpha1_clusterscan_vuln.yaml
  internal/saas/clusters.go
  internal/saas/clusters_test.go
Labels: bug :bug:

#267 Add documentation about vulnerability database persistence
  charts/zora/README.md
  charts/zora/templates/plugins/trivy-job.yaml
  charts/zora/templates/plugins/trivy-pvc.yaml
  charts/zora/values.yaml
  docs/configuration/vulnerability-database-persistence.md
  docs/plugins/trivy.md
  mkdocs.yml
Labels: documentation :page_facing_up:

#269 Bump dependencies and Go version
  .gitignore
  Makefile
  api/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/README.md
  charts/zora/crds/zora.undistro.io_clusterissues.yaml
  charts/zora/crds/zora.undistro.io_clusters.yaml
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  charts/zora/crds/zora.undistro.io_customchecks.yaml
  charts/zora/crds/zora.undistro.io_plugins.yaml
  charts/zora/crds/zora.undistro.io_vulnerabilityreports.yaml
  charts/zora/values.yaml
  cmd/Dockerfile
  cmd/worker/Dockerfile
  config/crd/bases/zora.undistro.io_clusterissues.yaml
  config/crd/bases/zora.undistro.io_clusters.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_customchecks.yaml
  config/crd/bases/zora.undistro.io_plugins.yaml
  config/crd/bases/zora.undistro.io_vulnerabilityreports.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clusterissues.yaml
  config/crd/patches/cainjection_in_clusters.yaml
  config/crd/patches/cainjection_in_clusterscans.yaml
  config/crd/patches/cainjection_in_plugins.yaml
  config/crd/patches/cainjection_in_zora_customchecks.yaml
  config/crd/patches/cainjection_in_zora_vulnerabilityreports.yaml
  config/crd/patches/webhook_in_clusterissues.yaml
  config/crd/patches/webhook_in_clusters.yaml
  config/crd/patches/webhook_in_clusterscans.yaml
  config/crd/patches/webhook_in_plugins.yaml
  config/crd/patches/webhook_in_zora_customchecks.yaml
  config/crd/patches/webhook_in_zora_vulnerabilityreports.yaml
  config/default/kustomization.yaml
  config/rbac/service_account.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/zora/suite_test.go
  pkg/discovery/zz_generated.deepcopy.go
Labels: dependencies

#270 Add `enable-http2` and `metrics-secure` flags
  cmd/main.go
Labels: enhancement

#273 Versioning binaries and add CONTAINER_TOOL variable in Makefile
  Makefile
Labels: enhancement

#271 Add update CRDs support
  charts/zora/README.md
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/operator/rbac.yaml
  charts/zora/values.yaml
  cmd/Dockerfile
  cmd/main.go
  config/crd/bases/embed.go
  config/crd/bases/embed_test.go
  config/rbac/role.yaml
  internal/controller/zora/customcheck_controller.go
  pkg/crds/crds.go
  pkg/crds/crds_test.go
Labels: enhancement

#274 bump marvin image version to 0.2.3
  charts/zora/Chart.yaml
  charts/zora/README.md
  charts/zora/values.yaml
Labels: bug :bug:

#275 Fix clientset generation and add for informers and listers
  Makefile
  api/zora/v1alpha1/cluster_types.go
  api/zora/v1alpha1/clusterissue_types.go
  api/zora/v1alpha1/clusterscan_types.go
  api/zora/v1alpha1/customcheck_types.go
  api/zora/v1alpha1/groupversion_info.go
  api/zora/v1alpha1/plugin_types.go
  api/zora/v1alpha1/vulnerabilityreport_types.go
  api/zora/v1alpha2/customcheck_types.go
  api/zora/v1alpha2/groupversion_info.go
  pkg/clientset/versioned/clientset.go
  pkg/clientset/versioned/fake/clientset_generated.go
  pkg/clientset/versioned/fake/register.go
  pkg/clientset/versioned/scheme/register.go
  pkg/clientset/versioned/typed/zora/v1alpha1/cluster.go
  pkg/clientset/versioned/typed/zora/v1alpha1/clusterissue.go
  pkg/clientset/versioned/typed/zora/v1alpha1/clusterscan.go
  pkg/clientset/versioned/typed/zora/v1alpha1/customcheck.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_cluster.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_clusterissue.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_clusterscan.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_customcheck.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_plugin.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_vulnerabilityreport.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_zora_client.go
  pkg/clientset/versioned/typed/zora/v1alpha1/generated_expansion.go
  pkg/clientset/versioned/typed/zora/v1alpha1/plugin.go
  pkg/clientset/versioned/typed/zora/v1alpha1/vulnerabilityreport.go
  pkg/clientset/versioned/typed/zora/v1alpha1/zora_client.go
  pkg/clientset/versioned/typed/zora/v1alpha2/customcheck.go
  pkg/clientset/versioned/typed/zora/v1alpha2/doc.go
  pkg/clientset/versioned/typed/zora/v1alpha2/fake/doc.go
  pkg/clientset/versioned/typed/zora/v1alpha2/fake/fake_customcheck.go
  pkg/clientset/versioned/typed/zora/v1alpha2/fake/fake_zora_client.go
  pkg/clientset/versioned/typed/zora/v1alpha2/generated_expansion.go
  pkg/clientset/versioned/typed/zora/v1alpha2/zora_client.go
  pkg/informers/externalversions/factory.go
  pkg/informers/externalversions/generic.go
  pkg/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/informers/externalversions/zora/interface.go
  pkg/informers/externalversions/zora/v1alpha1/cluster.go
  pkg/informers/externalversions/zora/v1alpha1/clusterissue.go
  pkg/informers/externalversions/zora/v1alpha1/clusterscan.go
  pkg/informers/externalversions/zora/v1alpha1/customcheck.go
  pkg/informers/externalversions/zora/v1alpha1/interface.go
  pkg/informers/externalversions/zora/v1alpha1/plugin.go
  pkg/informers/externalversions/zora/v1alpha1/vulnerabilityreport.go
  pkg/informers/externalversions/zora/v1alpha2/customcheck.go
  pkg/informers/externalversions/zora/v1alpha2/interface.go
  pkg/listers/zora/v1alpha1/cluster.go
  pkg/listers/zora/v1alpha1/clusterissue.go
  pkg/listers/zora/v1alpha1/clusterscan.go
  pkg/listers/zora/v1alpha1/customcheck.go
  pkg/listers/zora/v1alpha1/expansion_generated.go
  pkg/listers/zora/v1alpha1/plugin.go
  pkg/listers/zora/v1alpha1/vulnerabilityreport.go
  pkg/listers/zora/v1alpha2/customcheck.go
  pkg/listers/zora/v1alpha2/expansion_generated.go
Labels: bug :bug:

#276 Do not set volume mount when Trivy persistence is disabled
  charts/zora/Chart.yaml
  charts/zora/README.md
  pkg/plugins/cronjob.go
Labels: bug :bug:

#278 fix empty flags when Trivy persistence is disabled
  charts/zora/Chart.yaml
  charts/zora/README.md
  charts/zora/templates/operator/deployment.yaml
Labels: bug :bug:
