Repository undistro/zora, pull requests merged in 2024-01, with the labels that each got.

#232 Bump dependencies and include more image details in VulnerabilityReport
  .gitignore
  .golangci.yml
  Makefile
  api/zora/v1alpha1/clusterissue_types.go
  api/zora/v1alpha1/clusterscan_types.go
  api/zora/v1alpha1/vulnerabilityreport_types.go
  api/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/README.md
  charts/zora/crds/zora.undistro.io_clusterissues.yaml
  charts/zora/crds/zora.undistro.io_clusters.yaml
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  charts/zora/crds/zora.undistro.io_customchecks.yaml
  charts/zora/crds/zora.undistro.io_plugins.yaml
  charts/zora/crds/zora.undistro.io_vulnerabilityreports.yaml
  charts/zora/templates/plugins/trivy.yaml
  charts/zora/values.yaml
  cmd/main.go
  config/crd/bases/zora.undistro.io_clusterissues.yaml
  config/crd/bases/zora.undistro.io_clusters.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_customchecks.yaml
  config/crd/bases/zora.undistro.io_plugins.yaml
  config/crd/bases/zora.undistro.io_vulnerabilityreports.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/role.yaml
  config/samples/zora_v1alpha1_plugin_marvin.yaml
  config/samples/zora_v1alpha1_plugin_trivy.yaml
  docs/plugins/index.md
  docs/plugins/marvin.md
  docs/plugins/trivy.md
  go.mod
  go.sum
  internal/controller/zora/clusterscan_controller.go
  internal/controller/zora/suite_test.go
  pkg/clientset/versioned/doc.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_cluster.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_clusterissue.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_clusterscan.go
  pkg/clientset/versioned/typed/zora/v1alpha1/fake/fake_vulnerabilityreport.go
  pkg/discovery/zz_generated.deepcopy.go
  pkg/kubeconfig/config.go
  pkg/plugins/cronjob.go
  pkg/worker/config.go
  pkg/worker/config_test.go
  pkg/worker/misconfig.go
  pkg/worker/misconfig_test.go
  pkg/worker/report/marvin/parse.go
  pkg/worker/report/marvin/urls.go
  pkg/worker/report/popeye/parse.go
  pkg/worker/report/popeye/parse_types.go
  pkg/worker/report/popeye/parse_types_test.go
  pkg/worker/report/trivy/parse.go
  pkg/worker/report/trivy/parse_test.go
  pkg/worker/report/trivy/testdata/report.json
  pkg/worker/vuln.go
  pkg/worker/vuln_test.go
Labels: enhancement, dependencies

#233 Send vulnerability reports to SaaS when enabled
  api/zora/v1alpha1/vulnerabilityreport_types.go
  api/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/crds/zora.undistro.io_vulnerabilityreports.yaml
  charts/zora/templates/operator/rbac.yaml
  config/crd/bases/zora.undistro.io_vulnerabilityreports.yaml
  config/rbac/role.yaml
  internal/controller/zora/clusterscan_controller.go
  internal/saas/client.go
  internal/saas/clusters.go
  internal/saas/hooks.go
Labels: enhancement

#234 UD-1129: Update reconciliation of misconfigurations and vulnerabiliti…
  api/zora/v1alpha1/clusterscan_types.go
  api/zora/v1alpha1/zz_generated.deepcopy.go
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  internal/saas/hooks.go
Labels: bug :bug:

#237 UD-1141: Fix instances of stale scan ID information
  internal/controller/zora/clusterscan_controller.go
  internal/saas/clusters.go
  internal/saas/hooks.go
Labels: bug :bug:

#238 Release v0.8.0
  charts/zora/Chart.yaml
  charts/zora/README.md
  cmd/main.go
  docs/dashboard.md
  docs/getting-started/installation.md
  docs/plugins/index.md
  docs/plugins/trivy.md
  mkdocs.yml
Labels: documentation :page_facing_up:, enhancement
