Repository undistro/zora, pull requests merged in 2024-03, with the labels that each got.

#250 OpenShift support
  charts/zora/Chart.yaml
  charts/zora/README.md
  charts/zora/templates/plugins/trivy.yaml
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_trivy.yaml
  docs/configuration/authenticated-registries.md
  docs/configuration/private-registries/acr.md
  docs/configuration/private-registries/ecr.md
  docs/index.md
  docs/plugins/index.md
  docs/plugins/trivy.md
  mkdocs.yml
  pkg/discovery/cluster_labels.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
Labels: documentation :page_facing_up:, enhancement

#252 UD-1211: Switch trivy image over to the undistro spin
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_trivy.yaml
  docs/plugins/index.md
  docs/plugins/trivy.md
Labels: bug :bug:

#255 Pin setup-envtest to latest working build, fixes #253
  Makefile
Labels: bug :bug:

#254 docs: warn about costly scan scheduling in documentation
  docs/configuration/scan-schedule.md
Labels: documentation :page_facing_up:

#251 Avoid updating scans schedule on helm upgrades when not explicitly set
  charts/zora/templates/clusterscan/clusterscan.yaml
Labels: enhancement

#257 Update popeye worker integration for version v0.21.0
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  config/samples/zora_v1alpha1_plugin_popeye_all.yaml
  docs/plugins/index.md
  docs/plugins/popeye.md
  pkg/worker/report/popeye/parse.go
  pkg/worker/report/popeye/popeye_types.go
  pkg/worker/report/popeye/testdata/test_report_1.json
  pkg/worker/report/popeye/testdata/test_report_2.json
  pkg/worker/report/popeye/testdata/test_report_5.json
  pkg/worker/report/popeye/testdata/test_report_6.json
  pkg/worker/report/popeye/testdata/test_report_7.json
Labels: enhancement

#258 UD-1323: Update popeye parse_types to cover v0.21.1 messages
  pkg/worker/report/popeye/parse_types.go
  pkg/worker/report/popeye/parse_types_test.go
Labels: enhancement

#256 warn about costly scan scheduling in Helm output
  charts/zora/templates/NOTES.txt
  charts/zora/templates/_helpers.tpl
  charts/zora/templates/clusterscan/clusterscan.yaml
Labels: documentation :page_facing_up:

#259 UD-1338: Update trivy to 0.50.0
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_trivy.yaml
  docs/plugins/index.md
  docs/plugins/trivy.md
Labels: enhancement

#260 add line breaks in Helm NOTES.txt
  charts/zora/templates/NOTES.txt
Labels: documentation :page_facing_up:

#262 UD-1346: update poeye to v0.21.2
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_popeye.yaml
  config/samples/zora_v1alpha1_plugin_popeye_all.yaml
  docs/plugins/index.md
  docs/plugins/popeye.md
Labels: enhancement

#261 ci: update docs automatically on push to main
  .github/workflows/docs.yaml
Labels: documentation :page_facing_up:

#265 UD-1351: Update trivy to v0.50.1
  charts/zora/README.md
  charts/zora/values.yaml
  config/samples/zora_v1alpha1_plugin_trivy.yaml
  docs/plugins/index.md
  docs/plugins/trivy.md
Labels: enhancement
