Repository undistro/zora, pull requests merged in 2024-10, with the labels that each got.

#314 UD-1839 fix tokenrefresh template
  charts/zora/templates/tokenrefresh/rbac.yaml
Labels: bug :bug:

#315 UD-1829: Update documentation to include the oauth authorization process
  docs/assets/zora-dashboard-screenshot.png
  docs/assets/zora-device-confirmation.png
  docs/dashboard.md
  docs/getting-started/installation.md
Labels: documentation :page_facing_up:

#317 Update Zora Dashboard screenshots in documentation
  docs/assets/zora-dashboard-screenshot.png
  docs/assets/zora-device-confirmation.png
  docs/dashboard.md
  mkdocs.yml
Labels: documentation :page_facing_up:

#318 Add fsGroup variable for Trivy plugin
  charts/zora/Chart.yaml
  charts/zora/README.md
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/plugins/trivy-job.yaml
  charts/zora/values.yaml
  cmd/main.go
  docs/getting-started/installation.md
  internal/controller/zora/clusterscan_controller.go
  pkg/plugins/cronjob.go
Labels: enhancement
