Repository undistro/zora, pull requests merged in 2024-06, with the labels that each got.

#288 UD-1517: change name of the pvc and make sure files are accessible to…
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/plugins/trivy-job.yaml
  charts/zora/templates/plugins/trivy-pvc.yaml
Labels: bug :bug:

#287 fix: removing underscore from VulnerabilityReport names
  pkg/worker/vuln.go
  pkg/worker/vuln_test.go
Labels: bug :bug:

#295 UD-1541: Ensure both databases are downloaded on startup
  charts/zora/templates/plugins/trivy-job.yaml
Labels: bug :bug:

#294 UD-1540: Increase default size of PV to 2Gi
  charts/zora/README.md
  charts/zora/values.yaml
Labels: bug :bug:

#296 UD-1540: Rename pvc to support upgrade path
  charts/zora/templates/operator/deployment.yaml
  charts/zora/templates/plugins/trivy-job.yaml
  charts/zora/templates/plugins/trivy-pvc.yaml
Labels: bug :bug:

#297 Update default PVC size in documentation
  docs/configuration/vulnerability-database-persistence.md
Labels: documentation :page_facing_up:

#298 UD-1549: upgrade trivy and controller-runtime dependencies
  charts/zora/crds/zora.undistro.io_clusters.yaml
  charts/zora/crds/zora.undistro.io_clusterscans.yaml
  charts/zora/crds/zora.undistro.io_plugins.yaml
  cmd/Dockerfile
  cmd/worker/Dockerfile
  config/crd/bases/zora.undistro.io_clusters.yaml
  config/crd/bases/zora.undistro.io_clusterscans.yaml
  config/crd/bases/zora.undistro.io_plugins.yaml
  go.mod
  go.sum
Labels: dependencies

#300 fix VulnerabilityReport `totalUniquePackages`
  api/zora/v1alpha2/vulnerabilityreport_types.go
Labels: bug :bug:
